// Mocks generated by Mockito 5.4.4 from annotations
// in getir_mobile/test/unit/blocs/search_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:getir_mobile/core/errors/result.dart' as _i2;
import 'package:getir_mobile/core/services/search_history_service.dart' as _i8;
import 'package:getir_mobile/domain/entities/merchant.dart' as _i5;
import 'package:getir_mobile/domain/entities/product.dart' as _i7;
import 'package:getir_mobile/domain/services/merchant_service.dart' as _i3;
import 'package:getir_mobile/domain/services/product_service.dart' as _i6;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeResult_0<T> extends _i1.SmartFake implements _i2.Result<T> {
  _FakeResult_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [MerchantService].
///
/// See the documentation for Mockito's code generation for more information.
class MockMerchantService extends _i1.Mock implements _i3.MerchantService {
  MockMerchantService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Result<List<_i5.Merchant>>> getMerchants({
    int? page = 1,
    int? limit = 20,
    String? search,
    String? category,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMerchants,
          [],
          {
            #page: page,
            #limit: limit,
            #search: search,
            #category: category,
          },
        ),
        returnValue: _i4.Future<_i2.Result<List<_i5.Merchant>>>.value(
            _FakeResult_0<List<_i5.Merchant>>(
          this,
          Invocation.method(
            #getMerchants,
            [],
            {
              #page: page,
              #limit: limit,
              #search: search,
              #category: category,
            },
          ),
        )),
      ) as _i4.Future<_i2.Result<List<_i5.Merchant>>>);

  @override
  _i4.Future<_i2.Result<_i5.Merchant>> getMerchantById(String? merchantId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMerchantById,
          [merchantId],
        ),
        returnValue: _i4.Future<_i2.Result<_i5.Merchant>>.value(
            _FakeResult_0<_i5.Merchant>(
          this,
          Invocation.method(
            #getMerchantById,
            [merchantId],
          ),
        )),
      ) as _i4.Future<_i2.Result<_i5.Merchant>>);

  @override
  _i4.Future<_i2.Result<List<_i5.Merchant>>> searchMerchants(String? query) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchMerchants,
          [query],
        ),
        returnValue: _i4.Future<_i2.Result<List<_i5.Merchant>>>.value(
            _FakeResult_0<List<_i5.Merchant>>(
          this,
          Invocation.method(
            #searchMerchants,
            [query],
          ),
        )),
      ) as _i4.Future<_i2.Result<List<_i5.Merchant>>>);

  @override
  _i4.Future<_i2.Result<List<_i5.Merchant>>> getNearbyMerchants({
    required double? latitude,
    required double? longitude,
    double? radius = 5.0,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getNearbyMerchants,
          [],
          {
            #latitude: latitude,
            #longitude: longitude,
            #radius: radius,
          },
        ),
        returnValue: _i4.Future<_i2.Result<List<_i5.Merchant>>>.value(
            _FakeResult_0<List<_i5.Merchant>>(
          this,
          Invocation.method(
            #getNearbyMerchants,
            [],
            {
              #latitude: latitude,
              #longitude: longitude,
              #radius: radius,
            },
          ),
        )),
      ) as _i4.Future<_i2.Result<List<_i5.Merchant>>>);

  @override
  _i4.Future<_i2.Result<List<_i5.Merchant>>> getNearbyMerchantsByCategory({
    required double? latitude,
    required double? longitude,
    required int? categoryType,
    double? radius = 5.0,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getNearbyMerchantsByCategory,
          [],
          {
            #latitude: latitude,
            #longitude: longitude,
            #categoryType: categoryType,
            #radius: radius,
          },
        ),
        returnValue: _i4.Future<_i2.Result<List<_i5.Merchant>>>.value(
            _FakeResult_0<List<_i5.Merchant>>(
          this,
          Invocation.method(
            #getNearbyMerchantsByCategory,
            [],
            {
              #latitude: latitude,
              #longitude: longitude,
              #categoryType: categoryType,
              #radius: radius,
            },
          ),
        )),
      ) as _i4.Future<_i2.Result<List<_i5.Merchant>>>);
}

/// A class which mocks [ProductService].
///
/// See the documentation for Mockito's code generation for more information.
class MockProductService extends _i1.Mock implements _i6.ProductService {
  MockProductService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Result<List<_i7.Product>>> getProducts({
    int? page = 1,
    int? limit = 20,
    String? merchantId,
    String? category,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getProducts,
          [],
          {
            #page: page,
            #limit: limit,
            #merchantId: merchantId,
            #category: category,
          },
        ),
        returnValue: _i4.Future<_i2.Result<List<_i7.Product>>>.value(
            _FakeResult_0<List<_i7.Product>>(
          this,
          Invocation.method(
            #getProducts,
            [],
            {
              #page: page,
              #limit: limit,
              #merchantId: merchantId,
              #category: category,
            },
          ),
        )),
      ) as _i4.Future<_i2.Result<List<_i7.Product>>>);

  @override
  _i4.Future<_i2.Result<_i7.Product>> getProductById(String? productId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getProductById,
          [productId],
        ),
        returnValue: _i4.Future<_i2.Result<_i7.Product>>.value(
            _FakeResult_0<_i7.Product>(
          this,
          Invocation.method(
            #getProductById,
            [productId],
          ),
        )),
      ) as _i4.Future<_i2.Result<_i7.Product>>);

  @override
  _i4.Future<_i2.Result<List<_i7.Product>>> getProductsByMerchant(
          String? merchantId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getProductsByMerchant,
          [merchantId],
        ),
        returnValue: _i4.Future<_i2.Result<List<_i7.Product>>>.value(
            _FakeResult_0<List<_i7.Product>>(
          this,
          Invocation.method(
            #getProductsByMerchant,
            [merchantId],
          ),
        )),
      ) as _i4.Future<_i2.Result<List<_i7.Product>>>);

  @override
  _i4.Future<_i2.Result<List<_i7.Product>>> searchProducts(String? query) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchProducts,
          [query],
        ),
        returnValue: _i4.Future<_i2.Result<List<_i7.Product>>>.value(
            _FakeResult_0<List<_i7.Product>>(
          this,
          Invocation.method(
            #searchProducts,
            [query],
          ),
        )),
      ) as _i4.Future<_i2.Result<List<_i7.Product>>>);

  @override
  _i4.Future<_i2.Result<List<String>>> getCategories() => (super.noSuchMethod(
        Invocation.method(
          #getCategories,
          [],
        ),
        returnValue: _i4.Future<_i2.Result<List<String>>>.value(
            _FakeResult_0<List<String>>(
          this,
          Invocation.method(
            #getCategories,
            [],
          ),
        )),
      ) as _i4.Future<_i2.Result<List<String>>>);
}

/// A class which mocks [SearchHistoryService].
///
/// See the documentation for Mockito's code generation for more information.
class MockSearchHistoryService extends _i1.Mock
    implements _i8.SearchHistoryService {
  MockSearchHistoryService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<List<String>> getSearchHistory() => (super.noSuchMethod(
        Invocation.method(
          #getSearchHistory,
          [],
        ),
        returnValue: _i4.Future<List<String>>.value(<String>[]),
      ) as _i4.Future<List<String>>);

  @override
  _i4.Future<void> addSearchQuery(String? query) => (super.noSuchMethod(
        Invocation.method(
          #addSearchQuery,
          [query],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> removeSearchQuery(String? query) => (super.noSuchMethod(
        Invocation.method(
          #removeSearchQuery,
          [query],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> clearSearchHistory() => (super.noSuchMethod(
        Invocation.method(
          #clearSearchHistory,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<List<String>> getPopularSearches() => (super.noSuchMethod(
        Invocation.method(
          #getPopularSearches,
          [],
        ),
        returnValue: _i4.Future<List<String>>.value(<String>[]),
      ) as _i4.Future<List<String>>);
}
