// Mocks generated by Mockito 5.4.4 from annotations
// in getir_mobile/test/unit/services/pending_actions_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dio/dio.dart' as _i2;
import 'package:getir_mobile/core/services/local_storage_service.dart' as _i3;
import 'package:getir_mobile/core/services/logger_service.dart' as _i7;
import 'package:getir_mobile/core/services/network_service.dart' as _i5;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeDio_0 extends _i1.SmartFake implements _i2.Dio {
  _FakeDio_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [LocalStorageService].
///
/// See the documentation for Mockito's code generation for more information.
class MockLocalStorageService extends _i1.Mock
    implements _i3.LocalStorageService {
  MockLocalStorageService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<void> initialize() => (super.noSuchMethod(
        Invocation.method(
          #initialize,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> cacheApiResponse(
    String? endpoint,
    Map<String, dynamic>? data, {
    Duration? expiry,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #cacheApiResponse,
          [
            endpoint,
            data,
          ],
          {#expiry: expiry},
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> putCacheByKey(
    String? cacheKey,
    Map<String, dynamic>? data, {
    Duration? expiry,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #putCacheByKey,
          [
            cacheKey,
            data,
          ],
          {#expiry: expiry},
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<Map<String, dynamic>?> getCachedApiResponse(String? endpoint) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCachedApiResponse,
          [endpoint],
        ),
        returnValue: _i4.Future<Map<String, dynamic>?>.value(),
      ) as _i4.Future<Map<String, dynamic>?>);

  @override
  _i4.Future<Map<String, dynamic>?> getCacheByKey(String? cacheKey) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCacheByKey,
          [cacheKey],
        ),
        returnValue: _i4.Future<Map<String, dynamic>?>.value(),
      ) as _i4.Future<Map<String, dynamic>?>);

  @override
  _i4.Future<Map<String, dynamic>?> getRawCacheByKey(String? cacheKey) =>
      (super.noSuchMethod(
        Invocation.method(
          #getRawCacheByKey,
          [cacheKey],
        ),
        returnValue: _i4.Future<Map<String, dynamic>?>.value(),
      ) as _i4.Future<Map<String, dynamic>?>);

  @override
  _i4.Future<void> clearExpiredCache() => (super.noSuchMethod(
        Invocation.method(
          #clearExpiredCache,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> storeUserData(
    String? key,
    String? value,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #storeUserData,
          [
            key,
            value,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  String? getUserData(String? key) => (super.noSuchMethod(Invocation.method(
        #getUserData,
        [key],
      )) as String?);

  @override
  _i4.Future<String?> getUserDataAsync(String? key) => (super.noSuchMethod(
        Invocation.method(
          #getUserDataAsync,
          [key],
        ),
        returnValue: _i4.Future<String?>.value(),
      ) as _i4.Future<String?>);

  @override
  _i4.Future<void> removeUserData(String? key) => (super.noSuchMethod(
        Invocation.method(
          #removeUserData,
          [key],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> clearUserData() => (super.noSuchMethod(
        Invocation.method(
          #clearUserData,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> addToSyncQueue(
    String? action,
    Map<String, dynamic>? data,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #addToSyncQueue,
          [
            action,
            data,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  List<Map<String, dynamic>> getSyncQueue() => (super.noSuchMethod(
        Invocation.method(
          #getSyncQueue,
          [],
        ),
        returnValue: <Map<String, dynamic>>[],
      ) as List<Map<String, dynamic>>);

  @override
  _i4.Future<void> removeFromSyncQueue(int? index) => (super.noSuchMethod(
        Invocation.method(
          #removeFromSyncQueue,
          [index],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> updateSyncQueueRetryCount(
    int? index,
    int? retryCount,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateSyncQueueRetryCount,
          [
            index,
            retryCount,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> clearSyncQueue() => (super.noSuchMethod(
        Invocation.method(
          #clearSyncQueue,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  int getCacheSize() => (super.noSuchMethod(
        Invocation.method(
          #getCacheSize,
          [],
        ),
        returnValue: 0,
      ) as int);

  @override
  int getUserDataSize() => (super.noSuchMethod(
        Invocation.method(
          #getUserDataSize,
          [],
        ),
        returnValue: 0,
      ) as int);

  @override
  int getSyncQueueSize() => (super.noSuchMethod(
        Invocation.method(
          #getSyncQueueSize,
          [],
        ),
        returnValue: 0,
      ) as int);

  @override
  _i4.Future<void> clearAllCache() => (super.noSuchMethod(
        Invocation.method(
          #clearAllCache,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> removeCachedItem(String? cacheKey) => (super.noSuchMethod(
        Invocation.method(
          #removeCachedItem,
          [cacheKey],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> trimCacheToSize(int? maxSize) => (super.noSuchMethod(
        Invocation.method(
          #trimCacheToSize,
          [maxSize],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> dispose() => (super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}

/// A class which mocks [NetworkService].
///
/// See the documentation for Mockito's code generation for more information.
class MockNetworkService extends _i1.Mock implements _i5.NetworkService {
  MockNetworkService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.Dio get dio => (super.noSuchMethod(
        Invocation.getter(#dio),
        returnValue: _FakeDio_0(
          this,
          Invocation.getter(#dio),
        ),
      ) as _i2.Dio);

  @override
  bool get isOnline => (super.noSuchMethod(
        Invocation.getter(#isOnline),
        returnValue: false,
      ) as bool);

  @override
  _i4.Stream<bool> get networkStatusStream => (super.noSuchMethod(
        Invocation.getter(#networkStatusStream),
        returnValue: _i4.Stream<bool>.empty(),
      ) as _i4.Stream<bool>);

  @override
  _i4.Future<void> initialize() => (super.noSuchMethod(
        Invocation.method(
          #initialize,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<bool> isHostReachable(String? host) => (super.noSuchMethod(
        Invocation.method(
          #isHostReachable,
          [host],
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<String> getConnectionType() => (super.noSuchMethod(
        Invocation.method(
          #getConnectionType,
          [],
        ),
        returnValue: _i4.Future<String>.value(_i6.dummyValue<String>(
          this,
          Invocation.method(
            #getConnectionType,
            [],
          ),
        )),
      ) as _i4.Future<String>);

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [LoggerService].
///
/// See the documentation for Mockito's code generation for more information.
class MockLoggerService extends _i1.Mock implements _i7.LoggerService {
  MockLoggerService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  void setMinimumLevel(_i7.LogLevel? level) => super.noSuchMethod(
        Invocation.method(
          #setMinimumLevel,
          [level],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void debug(
    String? message, {
    String? tag,
    Map<String, dynamic>? context,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #debug,
          [message],
          {
            #tag: tag,
            #context: context,
          },
        ),
        returnValueForMissingStub: null,
      );

  @override
  void info(
    String? message, {
    String? tag,
    Map<String, dynamic>? context,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #info,
          [message],
          {
            #tag: tag,
            #context: context,
          },
        ),
        returnValueForMissingStub: null,
      );

  @override
  void warning(
    String? message, {
    String? tag,
    Map<String, dynamic>? context,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #warning,
          [message],
          {
            #tag: tag,
            #context: context,
          },
        ),
        returnValueForMissingStub: null,
      );

  @override
  void error(
    String? message, {
    String? tag,
    dynamic error,
    StackTrace? stackTrace,
    Map<String, dynamic>? context,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #error,
          [message],
          {
            #tag: tag,
            #error: error,
            #stackTrace: stackTrace,
            #context: context,
          },
        ),
        returnValueForMissingStub: null,
      );

  @override
  void fatal(
    String? message, {
    String? tag,
    required dynamic error,
    StackTrace? stackTrace,
    Map<String, dynamic>? context,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #fatal,
          [message],
          {
            #tag: tag,
            #error: error,
            #stackTrace: stackTrace,
            #context: context,
          },
        ),
        returnValueForMissingStub: null,
      );

  @override
  void logNetworkRequest({
    required String? method,
    required String? url,
    int? statusCode,
    Duration? duration,
    Map<String, dynamic>? headers,
    dynamic error,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #logNetworkRequest,
          [],
          {
            #method: method,
            #url: url,
            #statusCode: statusCode,
            #duration: duration,
            #headers: headers,
            #error: error,
          },
        ),
        returnValueForMissingStub: null,
      );

  @override
  void logBlocEvent({
    required String? blocName,
    required String? eventName,
    Map<String, dynamic>? eventData,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #logBlocEvent,
          [],
          {
            #blocName: blocName,
            #eventName: eventName,
            #eventData: eventData,
          },
        ),
        returnValueForMissingStub: null,
      );

  @override
  void logBlocStateChange({
    required String? blocName,
    required String? previousState,
    required String? newState,
    Map<String, dynamic>? stateData,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #logBlocStateChange,
          [],
          {
            #blocName: blocName,
            #previousState: previousState,
            #newState: newState,
            #stateData: stateData,
          },
        ),
        returnValueForMissingStub: null,
      );

  @override
  void logNavigation({
    required String? from,
    required String? to,
    Map<String, dynamic>? params,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #logNavigation,
          [],
          {
            #from: from,
            #to: to,
            #params: params,
          },
        ),
        returnValueForMissingStub: null,
      );

  @override
  void logUserAction({
    required String? action,
    String? screen,
    Map<String, dynamic>? details,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #logUserAction,
          [],
          {
            #action: action,
            #screen: screen,
            #details: details,
          },
        ),
        returnValueForMissingStub: null,
      );

  @override
  void logAuthEvent({
    required String? event,
    String? userId,
    Map<String, dynamic>? details,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #logAuthEvent,
          [],
          {
            #event: event,
            #userId: userId,
            #details: details,
          },
        ),
        returnValueForMissingStub: null,
      );

  @override
  void logDatabaseOperation({
    required String? operation,
    required String? table,
    bool? success = true,
    dynamic error,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #logDatabaseOperation,
          [],
          {
            #operation: operation,
            #table: table,
            #success: success,
            #error: error,
          },
        ),
        returnValueForMissingStub: null,
      );

  @override
  void logCacheOperation({
    required String? operation,
    required String? key,
    bool? hit = false,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #logCacheOperation,
          [],
          {
            #operation: operation,
            #key: key,
            #hit: hit,
          },
        ),
        returnValueForMissingStub: null,
      );

  @override
  void logPerformance({
    required String? operation,
    required Duration? duration,
    Map<String, dynamic>? metrics,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #logPerformance,
          [],
          {
            #operation: operation,
            #duration: duration,
            #metrics: metrics,
          },
        ),
        returnValueForMissingStub: null,
      );

  @override
  void logLifecycleEvent({
    required String? event,
    Map<String, dynamic>? details,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #logLifecycleEvent,
          [],
          {
            #event: event,
            #details: details,
          },
        ),
        returnValueForMissingStub: null,
      );

  @override
  void logSensitiveOperation({
    required String? operation,
    bool? success = true,
    dynamic error,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #logSensitiveOperation,
          [],
          {
            #operation: operation,
            #success: success,
            #error: error,
          },
        ),
        returnValueForMissingStub: null,
      );

  @override
  Map<String, dynamic> sanitizeData(Map<String, dynamic>? data) =>
      (super.noSuchMethod(
        Invocation.method(
          #sanitizeData,
          [data],
        ),
        returnValue: <String, dynamic>{},
      ) as Map<String, dynamic>);
}
