// Mocks generated by Mockito 5.4.4 from annotations
// in getir_mobile/test/unit/services/product_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:getir_mobile/core/errors/result.dart' as _i2;
import 'package:getir_mobile/domain/entities/product.dart' as _i5;
import 'package:getir_mobile/domain/repositories/product_repository.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeResult_0<T> extends _i1.SmartFake implements _i2.Result<T> {
  _FakeResult_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [IProductRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockIProductRepository extends _i1.Mock
    implements _i3.IProductRepository {
  MockIProductRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Result<List<_i5.Product>>> getProducts({
    int? page = 1,
    int? limit = 20,
    String? merchantId,
    String? category,
    String? search,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getProducts,
          [],
          {
            #page: page,
            #limit: limit,
            #merchantId: merchantId,
            #category: category,
            #search: search,
          },
        ),
        returnValue: _i4.Future<_i2.Result<List<_i5.Product>>>.value(
            _FakeResult_0<List<_i5.Product>>(
          this,
          Invocation.method(
            #getProducts,
            [],
            {
              #page: page,
              #limit: limit,
              #merchantId: merchantId,
              #category: category,
              #search: search,
            },
          ),
        )),
      ) as _i4.Future<_i2.Result<List<_i5.Product>>>);

  @override
  _i4.Future<_i2.Result<_i5.Product>> getProductById(String? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #getProductById,
          [id],
        ),
        returnValue: _i4.Future<_i2.Result<_i5.Product>>.value(
            _FakeResult_0<_i5.Product>(
          this,
          Invocation.method(
            #getProductById,
            [id],
          ),
        )),
      ) as _i4.Future<_i2.Result<_i5.Product>>);

  @override
  _i4.Future<_i2.Result<List<_i5.Product>>> getProductsByMerchant(
          String? merchantId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getProductsByMerchant,
          [merchantId],
        ),
        returnValue: _i4.Future<_i2.Result<List<_i5.Product>>>.value(
            _FakeResult_0<List<_i5.Product>>(
          this,
          Invocation.method(
            #getProductsByMerchant,
            [merchantId],
          ),
        )),
      ) as _i4.Future<_i2.Result<List<_i5.Product>>>);

  @override
  _i4.Future<_i2.Result<List<_i5.Product>>> searchProducts(String? query) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchProducts,
          [query],
        ),
        returnValue: _i4.Future<_i2.Result<List<_i5.Product>>>.value(
            _FakeResult_0<List<_i5.Product>>(
          this,
          Invocation.method(
            #searchProducts,
            [query],
          ),
        )),
      ) as _i4.Future<_i2.Result<List<_i5.Product>>>);

  @override
  _i4.Future<_i2.Result<List<String>>> getCategories() => (super.noSuchMethod(
        Invocation.method(
          #getCategories,
          [],
        ),
        returnValue: _i4.Future<_i2.Result<List<String>>>.value(
            _FakeResult_0<List<String>>(
          this,
          Invocation.method(
            #getCategories,
            [],
          ),
        )),
      ) as _i4.Future<_i2.Result<List<String>>>);
}
