// Mocks generated by Mockito 5.4.4 from annotations
// in getir_mobile/test/unit/services/review_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:getir_mobile/core/errors/result.dart' as _i2;
import 'package:getir_mobile/domain/entities/review.dart' as _i5;
import 'package:getir_mobile/domain/repositories/review_repository.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeResult_0<T> extends _i1.SmartFake implements _i2.Result<T> {
  _FakeResult_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [IReviewRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockIReviewRepository extends _i1.Mock implements _i3.IReviewRepository {
  MockIReviewRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Result<_i5.Review>> submitReview(
          _i5.SubmitReviewRequest? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #submitReview,
          [request],
        ),
        returnValue:
            _i4.Future<_i2.Result<_i5.Review>>.value(_FakeResult_0<_i5.Review>(
          this,
          Invocation.method(
            #submitReview,
            [request],
          ),
        )),
      ) as _i4.Future<_i2.Result<_i5.Review>>);

  @override
  _i4.Future<_i2.Result<List<_i5.Review>>> getMerchantReviews(
    String? merchantId, {
    int? page = 1,
    int? pageSize = 20,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMerchantReviews,
          [merchantId],
          {
            #page: page,
            #pageSize: pageSize,
          },
        ),
        returnValue: _i4.Future<_i2.Result<List<_i5.Review>>>.value(
            _FakeResult_0<List<_i5.Review>>(
          this,
          Invocation.method(
            #getMerchantReviews,
            [merchantId],
            {
              #page: page,
              #pageSize: pageSize,
            },
          ),
        )),
      ) as _i4.Future<_i2.Result<List<_i5.Review>>>);

  @override
  _i4.Future<_i2.Result<List<_i5.Review>>> getCourierReviews(
    String? courierId, {
    int? page = 1,
    int? pageSize = 20,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCourierReviews,
          [courierId],
          {
            #page: page,
            #pageSize: pageSize,
          },
        ),
        returnValue: _i4.Future<_i2.Result<List<_i5.Review>>>.value(
            _FakeResult_0<List<_i5.Review>>(
          this,
          Invocation.method(
            #getCourierReviews,
            [courierId],
            {
              #page: page,
              #pageSize: pageSize,
            },
          ),
        )),
      ) as _i4.Future<_i2.Result<List<_i5.Review>>>);

  @override
  _i4.Future<_i2.Result<_i5.Review>> getReviewById(String? reviewId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getReviewById,
          [reviewId],
        ),
        returnValue:
            _i4.Future<_i2.Result<_i5.Review>>.value(_FakeResult_0<_i5.Review>(
          this,
          Invocation.method(
            #getReviewById,
            [reviewId],
          ),
        )),
      ) as _i4.Future<_i2.Result<_i5.Review>>);

  @override
  _i4.Future<_i2.Result<void>> markReviewAsHelpful(String? reviewId) =>
      (super.noSuchMethod(
        Invocation.method(
          #markReviewAsHelpful,
          [reviewId],
        ),
        returnValue: _i4.Future<_i2.Result<void>>.value(_FakeResult_0<void>(
          this,
          Invocation.method(
            #markReviewAsHelpful,
            [reviewId],
          ),
        )),
      ) as _i4.Future<_i2.Result<void>>);

  @override
  _i4.Future<_i2.Result<_i5.Review>> updateReview(
    String? reviewId, {
    int? rating,
    String? comment,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateReview,
          [reviewId],
          {
            #rating: rating,
            #comment: comment,
          },
        ),
        returnValue:
            _i4.Future<_i2.Result<_i5.Review>>.value(_FakeResult_0<_i5.Review>(
          this,
          Invocation.method(
            #updateReview,
            [reviewId],
            {
              #rating: rating,
              #comment: comment,
            },
          ),
        )),
      ) as _i4.Future<_i2.Result<_i5.Review>>);

  @override
  _i4.Future<_i2.Result<void>> deleteReview(String? reviewId) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteReview,
          [reviewId],
        ),
        returnValue: _i4.Future<_i2.Result<void>>.value(_FakeResult_0<void>(
          this,
          Invocation.method(
            #deleteReview,
            [reviewId],
          ),
        )),
      ) as _i4.Future<_i2.Result<void>>);
}
