arb-dir: l10n
template-arb-file: app_en.arb
output-localization-file: app_localizations.g.dart
output-class: GeneratedLocalizations
synthetic-package: false
nullable-getter: false
untranslated-messages-file: l10n_untranslated.txt

